### ISSUE TITLE
미디어 웹 서비스 개발 FE 1-2

### ISSUE THREAD

**Issue by 6mn12j** [6mn12j/projectX-MediaWebService#3]
- [x] 1. 대표이미지를 추가합니다. 썸네일 이미지 영역을 설정하고 ID or Name 값을 추가 합니다. 
- [x] 2. 제목 1줄을 추가합니다. 제목 영역을 설정하고 ID or Name 값을 추가 합니다. 
- [x] 3. 내용 2줄을 추가합니다. 제목 영역을 설정하고 ID or Name 값을 추가 합니다. 
- [x] 4. 작성된 모든 코드는 파일명을 다르게 하고 git 으로 형상 관리를 진행합니다.

**Comment by 6mn12j** [comment]
- **css로 텍스트 라인 수 제한하기**
-멀티라인 줄 수 제한
  ```css
  .title {
    overflow: hidden;
    padding: 4px;
    text-overflow: ellipsis;
    display: -webkit-box;
    line-height: 18px;
    max-height: 32px;
    -webkit-line-clamp: 2; /* 표시하고자 하는 라인 수 */
    -webkit-box-orient: vertical;
  }
  ```
